sudo: required

services:
  - docker
  - mysql

language: java
jdk: oraclejdk8

script: ./compile.sh all

before_install:
  - mysql -e 'CREATE DATABASE account_test;'
  - mysql -e 'CREATE DATABASE auth_test;'
  - mysql -e 'CREATE DATABASE election_test;'
  - chmod a+x compile.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)