sudo: required

services:
  - docker
  - mysql

language: java
jdk: oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - BACKEND_VER=0.1.0

script: ./compile.sh

before_install:

  - mysql -e 'CREATE DATABASE mediayanglebihbaik_test;'
  - chmod a+x compile.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "travis-docker" ]; then

    fi

  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

  # BACKEND
  - export BACKEND=imrenagi/rojak-backend
  - docker build -t $BACKEND:$BACKEND_VER .
  - docker tag $BACKEND:$BACKEND_VER $BACKEND:$BACKEND_VER
  - docker push $BACKEND
